version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.12-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5


  migrate:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://taskuser:taskpass@postgres:5432/taskdb
    command: alembic upgrade head
    restart: "no"

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://taskuser:taskpass@postgres:5432/taskdb
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  relay:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: postgresql+asyncpg://taskuser:taskpass@postgres:5432/taskdb
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    volumes:
      - .:/app
    command: python -m app.workers.relay
    restart: unless-stopped
    deploy:
      replicas: 3   # масштабирование воркеров

  task_worker:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: postgresql+asyncpg://taskuser:taskpass@postgres:5432/taskdb
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    volumes:
      - .:/app
    command: python -m app.workers.task_worker
    restart: unless-stopped
    deploy:
      replicas: 3   # масштабирование воркеров

volumes:
  postgres_data: